### ISSUE TITLE
Running in official Docker image

### ISSUE THREAD

**Issue by chbndrhnns** [JeffLIrion/homeassistant_native_firetv#17]
I am running homeassistant using the [Docker image](https://hub.docker.com/r/homeassistant/home-assistant/). Do you have an idea how I can configure and use this script with the image? I assume the firetv package would need to be installed somehow on startup. I now see only this error message in hass:

```
components/media_player/firetv.py (ERROR):
Could not connect to firetv-server at localhost
```

**Comment by JeffLIrion** [comment]
You shouldn't need to install anything. However, it looks like your configuration is incorrect. Please follow the instructions in the README, or see the HTML documentation here: https://deploy-preview-7062--home-assistant-docs.netlify.com/components/media_player.firetv/

**Comment by chbndrhnns** [comment]
I am one step further - I did not specify the Fire TV IP but localhost where the firetv-server was supposed to be running. Now I see this error:

```
Error while setting up platform firetv
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/firetv.py", line 62, in setup_platform
    device = FireTVDevice(host, name, adbkey, get_source, get_sources)
  File "/config/custom_components/media_player/firetv.py", line 115, in __init__
    from firetv import FireTV
ImportError: cannot import name 'FireTV'
```

Am I right that this is about a missing package?

**Comment by chbndrhnns** [comment]
Got it working. Was using localhost as IP address instead of the FireTV address which did not work.
