### ISSUE TITLE
Please add tracker.json for custom_updater

### ISSUE THREAD

**Issue by dasmaeh** [JeffLIrion/homeassistant_native_firetv#18]
The [custom_updater](https://github.com/custom-components/custom_updater) component allows an easy management of all custom components and cards within home assistant. 
It would be great if you could add a `tracker.json` file to allow easy updates of your component.

**Comment by JeffLIrion** [comment]
I'm trying to get this component merged into HA (see https://github.com/home-assistant/home-assistant/pull/17767). Since it looks like this `custom_updater` component is only relevant for custom components, I'm going to hold off on doing this. However, you're welcome to submit a pull request!
