### ISSUE TITLE
Hass.io ADB Key config error

### ISSUE THREAD

**Issue by trektronic** [JeffLIrion/homeassistant_native_firetv#19]
I am running Hass.io and am trying to set up a firetv with ADB key. I keep getting 'Invalid config' error. 

I have restarted the fire stick, and the raspberry pi running home assistant. I made sure to disconnect from my windows PC. I have the adbkey both files in /config/android/ folder. I made sure to always allow connections on the fire stick. I have also tried updating home assistant to 0.82.1

my configuration.yaml looks like this. 
```
media_player:
  - platform: firetv
    name: Fire TV
    host: 192.168.0.21
    adbkey: "/config/andriod/adbkey"

```

Error as shown in log: 

> 2018-11-27 01:57:42 ERROR (SyncWorker_12) [homeassistant.util.package] Unable to install package firetv==1.0.7: Failed building wheel for pycryptodome
> python-jose-cryptodome 1.3.2 has requirement pycryptodome<3.4.0,>=3.3.1, but you'll have pycryptodome 3.7.2 which is incompatible.
> pyrebase4 4.2.0 has requirement oauth2client==4.1.2, but you'll have oauth2client 4.0.0 which is incompatible.
> broadlink 0.9 has requirement pycryptodome==3.4.11, but you'll have pycryptodome 3.7.2 which is incompatible.
> Command "/usr/local/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-6zptawjf/pycryptodome/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-9d65ucv1/install-record.txt --single-version-externally-managed --prefix  --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-6zptawjf/pycryptodome/
> You are using pip version 18.0, however version 18.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> 2018-11-27 01:57:42 ERROR (MainThread) [homeassistant.requirements] Not initializing media_player.firetv because could not install requirement firetv==1.0.7
> 2018-11-27 01:57:42 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform media_player.firetv: Could not install all requirements.
> 

Am I setting this up wrong somehow? or do i need to do another step? 

I also wasn't sure how I can give homeassistant permissions for the adbkey while using hass.io?

**Comment by JeffLIrion** [comment]
This is probably the underlying issue: https://github.com/home-assistant/home-assistant/issues/17929

Also, you misspelled “android” in your configuration.

**Comment by trektronic** [comment]
Well, thanks for the information. Doesn't seem like I am gonna get it to work. 

I have flashed my sd under a fresh install and tried it under version: 0.82.1, 0.80.3, 0.80.2, 0.79.2

Every version says essentially the same thing in the log, that it failed building wheel for pycryptodome and versions are incompatible. 0.79.2 looked even worse with far more things being incompatible. 

I guess I will disable the component for now and hope they get around to that issue #17929. 

Thanks for the help. 

Out of curiosity, it suggests upgrading pip, which I cannot, or at least don't know how to, do using hass.io; however, would I maybe have been able to get this to work had I set it up soon after 0.82.1 dropped?

**Comment by JeffLIrion** [comment]
Multiple people have had this issue and I'm not sure what the underlying cause is. This updated Fire TV component will be in the next HA release (0.83), so at that point I think there shouldn't be any issues with installing the `firetv` package and its dependencies, most notably `pycryptodome`.

**Comment by JeffLIrion** [comment]
Also, don't worry about upgrading pip.

**Comment by trektronic** [comment]
In case anyone else runs into this issue, I was able to get the firetv component working under the beta version 0.83.0b1. 

Thanks for the help!
