### ISSUE TITLE
volume controls

### ISSUE THREAD

**Issue by uchagani** [JeffLIrion/homeassistant_native_firetv#20]
are volume controls supposed to work?  i see there is implementation for it but wasn't sure if there was something else i needed to do.

**Comment by JeffLIrion** [comment]
You know, I've never really looked into that part of the component. I think it might work if you import `SUPPORT_VOLUME_STEP` and add it to the `SUPPORT_FIRETV` variable.

**Comment by JeffLIrion** [comment]
On closer inspection, volume control is not implemented in the HA component.  You can try playing around with it using [this version](https://github.com/JeffLIrion/homeassistant_native_firetv/blob/pure-python-adb/media_player/firetv.py) of the component.  It registers a service called `media_player.firetv_adb_shell`.  According to these [key codes](https://github.com/JeffLIrion/homeassistant_native_firetv/blob/pure-python-adb/media_player/firetv.py), you should be able to adjust the volume using

```json
{"entity_id": "media_player.fire_tv_living_room", "cmd": "input keyevent <KEY>"}
```

where some relevant volume keys are:

* Volume up: 24
* Volume down: 25
* Volume mute: 164
* Mute: 91

I tried those myself just now but it didn't seem to do anything.

**Comment by JeffLIrion** [comment]
I removed volume support, since it wasn't actually implemented and the ADB commands didn't seem to work.
