### ISSUE TITLE
Missing "firetv" python module

### ISSUE THREAD

**Issue by nbonfire** [JeffLIrion/homeassistant_native_firetv#6]
I'm installing this with the home assistant docker container.

I was under the impression there were no other requirements for this component, but I get this error in the log:
```
2018-09-24 00:26:34 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform firetv
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/firetv.py", line 55, in setup_platform
    device = FireTVDevice(host, name, adbkey)
  File "/config/custom_components/media_player/firetv.py", line 90, in __init__
    from firetv import FireTV
ModuleNotFoundError: No module named 'firetv'
```

I was able to resolve this by going into the container and installing the required packages, but that's going to get wiped when the container is updated. Maybe there's a better way to get the packages installed that I don't know of...

**Comment by JeffLIrion** [comment]
I haven't used HA in a docker container so I'm not sure what difference that makes, if any. But HA should handle the dependencies for you. In the thread on the forum, user Rudertier got the same issue as you (except he was using Hass.io), and he said that it magically fixed itself (https://community.home-assistant.io/t/native-support-for-fire-tv/64448/42). My guess is that sometimes HA fails to install dependencies from Github. Please try restarting HA and if that doesn't work after a few tries then report back.

**Comment by nbonfire** [comment]
Will do.

**Comment by JeffLIrion** [comment]
Any update on this?

**Comment by signaleleven** [comment]
I had the same problem, in hassio. A subsequent restart of HA solved the issue. It looks like the dependency is downloaded on the first run, but not found (perhaps it's continuing asynchronously without waiting for the installation?) 
Anyway, I googled and  saw reference of this problem with other custom_components (eg https://github.com/nikrolls/homeassistant-goldair-heater/issues/1 - somewhere in this thread among other problems).
It's probably an hassio quirk with dependencies. Nothing wrong with the library (by the way, thanks!)

**Comment by JeffLIrion** [comment]
Cool, I'll go ahead and close this.  Also, I added a "Troubleshooting" section to the README and addressed this issue.  (https://github.com/JeffLIrion/homeassistant_native_firetv/commit/606c23b0f1a722c1b0e3e01dd571508b9052e5f8)
