### ISSUE TITLE
ADB Connection Intermitant

### ISSUE THREAD

**Issue by photinus** [JeffLIrion/homeassistant_native_firetv#7]
I'm seeing the status of the single firetv I have setup flap between unknown and connected. 

The error in the HA Log is:
Update encountered an exception; will attempt to re-establish the ADB connection in the next update

**Comment by JeffLIrion** [comment]
Does it successfully re-establish the ADB connection?

**Comment by photinus** [comment]
It seems so, but looses it pretty quickly. Here is a snippit of this mornings logs, though it only seems to happen when the fire tv is "awake"

Update encountered an exception; will attempt to re-establish the ADB connection in the next update
7:11 AM custom_components/media_player/firetv.py (ERROR)
Update encountered an exception; will attempt to re-establish the ADB connection in the next update
7:11 AM custom_components/media_player/firetv.py (ERROR)
Update encountered an exception; will attempt to re-establish the ADB connection in the next update
7:10 AM custom_components/media_player/firetv.py (ERROR)

When it's in the unknown state it wont accept any commands either. 

This is a model 2017 Pendant style Fire TV. It has a solid wifi connection with no dropped pings over a few minutes while experiencing the issue.

**Comment by JeffLIrion** [comment]
Are you sending a lot of commands to the Fire TV from Home Assistant when this occurs? If so, that's a known limitation for which I implemented a work-around, but if you send a lot of commands you'll cause the error that you're encountering.

**Comment by photinus** [comment]
Not sending any commands, that's just the idle behavior when the device is on or playing content. Attempting to send commands to the Fire TV is failing 2 out of 3 times.

**Comment by JeffLIrion** [comment]
What's your setup? HA installation type, HA version, host system hardware, etc.

**Comment by photinus** [comment]
Hassio vm image (running in vmware)
HA 0.78.3
Dual Xeon E5-2620 @ 2ghz (Hex Core)

VM is configured with 2 vCPUs (not showing heavy load) and 1gb ram. I've increased both just to be safe, but it doesn't seem to be a resource problem.

**Comment by JeffLIrion** [comment]
My guess is that it's an issue with your virtual machine. Do you have any other components that do local polling, and if so, do they give you issues?

**Comment by photinus** [comment]
Hmm... I'll keep poking around. None of the other local polling components have any issues. I have the Vizio Smartcast component running without issue. The VM does seem to like having more ram, but this issue persists. The only thing of note so far is that it's only happening when the firetv is active. If it goes to sleep (tv gets turned off) it keeps it connection just fine.

**Comment by JeffLIrion** [comment]
That makes some sense, given that only one ADB command is necessary when the Fire TV is off.  (https://github.com/JeffLIrion/homeassistant_native_firetv/blob/master/media_player/firetv.py#L130)

I still think this issue is due to your virtual machine.  Perhaps it's interfering with the ADB connection?

**Comment by JeffLIrion** [comment]
My suggestion is to install Home Assistant in a different way (e.g., Python virtual environment or Docker container), copy over your configuration, and see if the issue persists.  If it doesn't, then the virtual machine is more than likely causing the issue.

**Comment by JeffLIrion** [comment]
Thanks for investigating that!  I've only got Fire TV sticks, so I was unaware that another version might return a much longer list of sources.  Please let me know how the docker instance works out!

**Comment by photinus** [comment]
Same error with the connection to the Pendant Fire TV from a docker instance of Home Assistant (same version, only component setup is the same fire tv). I did remove it from my other HA config before testing with the docker instance.

**Comment by JeffLIrion** [comment]
Here is the function that gets the list of running apps: 
https://github.com/JeffLIrion/python-firetv/blob/master/firetv/__init__.py#L148

And that function then calls this one: 
https://github.com/JeffLIrion/python-firetv/blob/master/firetv/__init__.py#L488

You'd have to translate those Python commands into ADB commands.

**Comment by photinus** [comment]
I'll give those a shot tonight, if nothing else I can gather the list from the pendant and the stick and see what is different.

**Comment by photinus** [comment]
So, It's pulling back a filtered list of adb shell ps

I do see one odd-ball coming back from the pendant, the logcat line is oddly formatted and the WCHAN column has a very different output. I'm not really fluent with Python (though can generally understand what is going on) but I'm not sure what is throwing things off.

Pendant:
`USER      PID   PPID  VSIZE  RSS   WCHAN            PC  NAME
u0_a121   1910  3125  1029052 49952 SyS_epoll_ 00000000 S com.amazon.tv.livetv
u0_a2     3744  3125  1011992 34504 SyS_epoll_ 00000000 S com.android.proxyhandler
u0_a26    3897  3125  1008364 25140 SyS_epoll_ 00000000 S android.ext.services
u0_a134   3922  3125  1005976 25296 SyS_epoll_ 00000000 S com.amazon.net.smartconnect.SmartConnectService
u0_a100   3930  3125  1100308 51888 SyS_epoll_ 00000000 S com.amazon.vizzini
u0_a74    3947  3125  1018420 40888 SyS_epoll_ 00000000 S com.amazon.imp
u0_a86    3964  3125  1048384 47132 SyS_epoll_ 00000000 S com.amazon.tcomm
u0_a91    4015  3125  1894480 99820 SyS_epoll_ 00000000 S com.amazon.tv.launcher
u0_a98    4048  3125  1776496 87000 SyS_epoll_ 00000000 S com.amazon.venezia
u0_a39    4061  3125  1064208 43620 SyS_epoll_ 00000000 S com.amazon.client.metrics
u0_a39    4165  4061  4008   1372  __skb_recv 00000000 S logcat
u0_a78    4214  3125  1039660 46968 SyS_epoll_ 00000000 S com.amazon.kso.blackbird:BlackbirdServiceProcess
u0_a90    4335  3125  1017064 37584 SyS_epoll_ 00000000 S com.amazon.tv.ime
u0_a9     4797  3125  1018696 30628 SyS_epoll_ 00000000 S com.amazon.connectivitycontroller
u0_a61    5254  3125  1726908 43236 SyS_epoll_ 00000000 S com.amazon.bueller.music
u0_a24    5404  3125  1025172 37032 SyS_epoll_ 00000000 S com.amazon.discoveryservice.core.android
u0_a55    5548  3125  1067320 43396 SyS_epoll_ 00000000 S com.amazon.whisperlink.core.android
u0_a124   5647  3125  1237340 138700 SyS_epoll_ 00000000 S com.netflix.ninja
u0_a129   5998  3125  1065676 58724 SyS_epoll_ 00000000 S de.cyberdream.firenotifications.amazon
u0_a60    25545 3125  1779372 89040 SyS_epoll_ 00000000 S com.amazon.avod
u0_a104   25603 3125  1014896 25112 SyS_epoll_ 00000000 S com.amazon.webview.chromium:AWVMetricsProcess
u0_a49    25693 3125  1005220 26088 SyS_epoll_ 00000000 S com.android.providers.tv
u0_a19    26330 3125  1025680 38084 SyS_epoll_ 00000000 S com.amazon.device.messaging
u0_a62    27336 3125  1219616 128468 SyS_epoll_ 00000000 S com.amazon.bueller.photos
u0_a123   29699 3125  1700068 50016 SyS_epoll_ 00000000 S com.plexapp.android
u0_a126   31187 3125  1032200 42600 SyS_epoll_ 00000000 S com.amazon.cloud9
u0_a122   31200 3125  1697588 39124 SyS_epoll_ 00000000 S com.att.tv
u0_a78    31606 3125  1017456 32144 SyS_epoll_ 00000000 S com.amazon.kso.blackbird
`

Stick:
`USER     PID   PPID  VSIZE  RSS     WCHAN    PC        NAME
amz_u0a68 1946  207   1003788 8964  ffffffff 00000000 S com.amazon.tv.ime
amz_u0a76 1981  207   1098068 24848 ffffffff 00000000 S com.amazon.vizzini
amz_u0a51 2003  207   1000308 23864 ffffffff 00000000 S com.amazon.imp
amz_u0a64 2050  207   1028384 28700 ffffffff 00000000 S com.amazon.tcomm
amz_u0a26 2277  207   1038964 25856 ffffffff 00000000 S com.amazon.client.metrics
amz_u0a26 2399  2277  1060   240   ffffffff 00000000 S logcat
amz_u0a95 3326  207   1011360 37912 ffffffff 00000000 S com.amazon.tv.livetv
amz_u0a86 3567  207   999068 20296 ffffffff 00000000 S com.amazon.webview.chromium:AWVArcusServiceProcess
amz_u0a35 5243  207   1049940 26240 ffffffff 00000000 S com.amazon.whisperlink.core.android
amz_u0a86 6082  207   1000108 9164  ffffffff 00000000 S com.amazon.webview.chromium:AWVMetricsProcess
u0_a26    6102  207   1133060 23264 ffffffff 00000000 S de.cyberdream.firenotifications.amazon
amz_u0a83 9152  207   993136 20316 ffffffff 00000000 S com.android.providers.tv
amz_u0a69 10862 207   1189240 80848 ffffffff 00000000 S com.amazon.tv.launcher
amz_u0a89 16320 207   1008396 28884 ffffffff 00000000 S com.amazon.discoveryservice.core.android
u0_a16    21444 207   1176244 119900 ffffffff 00000000 S com.netflix.ninja
amz_u0a39 24097 207   1072476 36192 ffffffff 00000000 S com.amazon.avod
u0_a18    25092 207   1041096 40580 ffffffff 00000000 S com.plexapp.android
amz_u0a62 31815 207   1021956 11832 ffffffff 00000000 S com.amazon.storm.lightning.services
amz_u0a55 31846 207   1008036 39152 ffffffff 00000000 S com.amazon.kso.blackbird:BlackbirdServiceProcess
amz_u0a55 31869 207   1003124 20872 ffffffff 00000000 S com.amazon.kso.blackbird
amz_u0a73 32292 207   1068924 58492 ffffffff 00000000 S com.amazon.venezia`

**Comment by photinus** [comment]
So, I get a similar crash if I try and use a different implementation of the python firetv server that has implemented the adbkeys, Looks like it might be something in the python adb library. I'll probably just hack together some functionality that doesn't involve pulling the list (or just use this on my firetv sticks)

**Comment by photinus** [comment]
I commented out that line in the module file and it is running and stable with the caveat of home assistant not seeing any "sources". I might dig into it some more and try and do some debugging. I did try setting up another one of the firetv server implementations and it crashes as well (though with different errors) which lead me to think it's actually an issue in the Google python adb library

**Comment by JeffLIrion** [comment]
OK, here's an easier way to debug this.  

In the terminal:
```bash
# make a virtual environment
mkvirtualenv --python=python3 firetv_test

workon firetv_test
pip install pycryptodome rsa
pip install https://github.com/JeffLIrion/python-adb/zipball/master
pip install https://github.com/JeffLIrion/python-firetv/zipball/master
```

While in the virtual environment, run this script (modify the path to the `adbkey` as needed):
```python
import firetv

host = '192.168.1.111:5555'
adbkey = '/config/android/adbkey'
f = firetv.FireTV(host, adbkey)

# get the running apps
x = f.running_apps()

# get the running apps "manually"
ps = f._adb.StreamingShell('ps')

# everything returned
bad_lines = list(ps)
bad_lines_formatted = '\n'.join([line for bad_line in bad_lines for line in bad_line.splitlines()])

# filter the running apps
result = [line.strip().rsplit(' ',1)[-1] for bad_line in bad_lines for line in bad_line.splitlines() if 'u0_a' in line]

print('\n\nRunning apps (from firetv)\n{0}\n{1}'.format('-'*26, x))
print('\n\nEverything returned\n{0}\n{1}'.format('-'*19, bad_lines_formatted))
print('\n\nFiltered running apps\n{0}\n{1}'.format('-'*21, result))
```

**Comment by photinus** [comment]
Set that up this morning and here is the resulting error:
Data_length 1582 does not match actual number of bytes read: 1424
Data_length 4095 does not match actual number of bytes read: 1424
Data_length 925 does not match actual number of bytes read: 201
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    bad_lines = list(ps)
  File "/root/.virtualenvs/firetv_test/lib/python3.5/site-packages/adb/adb_protocol.py", line 439, in StreamingCommand
    for data in connection.ReadUntilClose():
AttributeError: 'NoneType' object has no attribute 'ReadUntilClose'

**Comment by JeffLIrion** [comment]
Based on what you found, my theory is that the error is because the `current_app` command runs before the `running_apps` command has finished. Please try this modified file and let me know if that fixes it. 
https://github.com/JeffLIrion/homeassistant_native_firetv/blob/fix-issue7/media_player/firetv.py

**Comment by photinus** [comment]
Still getting the disconnects in the HA log.

**Comment by JeffLIrion** [comment]
OK, I guess showing the running apps as sources just isn't going to work for you.  This work-around seems like the best option.  

Updated `firetv.py` file: https://github.com/JeffLIrion/homeassistant_native_firetv/blob/fix-issue7/media_player/firetv.py

Updated configuration (note the `get_sources: false` entry)
```yaml
media_player:
  - platform: vizio
    host: 172.20.0.58
    access_token: <redacted>
  - platform: firetv
    name: livingroomfire
    host: 192.168.1.111
    adbkey: "/config/android/adbkey"
    get_sources: false
  - platform: firetv
    name: masterbedfire
    host: 192.168.1.112
    adbkey: "/config/android/adbkey"
```

**Comment by photinus** [comment]
Awesome, Thanks for that!

**Comment by JeffLIrion** [comment]
Is it working correctly now and not giving you errors?

**Comment by photinus** [comment]
Still throwing occasional errors, it doesn't seem to be throwing errors as often, but it's still doing it.

**Comment by JeffLIrion** [comment]
Damn, this error just won't give up! Maybe the best solution (I *think* this should be possible) would be to enable ADB commands using the `adb` binaries via system calls in Python rather than the `adb` package.

**Comment by JeffLIrion** [comment]
I added a `get_source` option.  If you set it to false, it won't retrieve the current app and the state won't be able to differentiate between "standby" and "paused" (it will be "standby").  

Updated firetv.py file: https://github.com/JeffLIrion/homeassistant_native_firetv/blob/fix-issue7/media_player/firetv.py

Updated configuration (note the `get_source: false` entry)

```yaml
media_player:
  - platform: vizio
    host: 172.20.0.58
    access_token: <redacted>
  - platform: firetv
    name: livingroomfire
    host: 192.168.1.111
    adbkey: "/config/android/adbkey"
    get_source: false
    get_sources: false
  - platform: firetv
    name: masterbedfire
    host: 192.168.1.112
    adbkey: "/config/android/adbkey"
```

**Comment by maddog986** [comment]
I was also having the re-establish errors. The update you just posted yesterday seems to have fixed it for me when adding "get_sources: false" to my media_player plex config.

**Comment by JeffLIrion** [comment]
> I was also having the re-establish errors. The update you just posted yesterday seems to have fixed it for me when adding "get_sources: false" to my media_player plex config.

I assume "plex" is a typo and that you meant firetv...

Is it working error-free now?  And what model of Fire TV device are you using?

**Comment by maddog986** [comment]
Yes sorry, was doing plex configs at the same. Using two FireTV Sticks Gen2 and the newer FireTV. All 3 required adb key authentication.

**Comment by JeffLIrion** [comment]
Which one(s) were getting those errors?

**Comment by maddog986** [comment]
All 3 had the errors.

**Comment by JeffLIrion** [comment]
That's interesting, photinus was only having issues with the pendant style Fire TV, his Fire TV sticks were working just fine.  

What's your Home Assistant setup?  (HA version, Hass.io / docker / virtual environment / etc., host system and hardware)

**Comment by JeffLIrion** [comment]
I merged these workarounds into the master branch (https://github.com/JeffLIrion/homeassistant_native_firetv/commit/9db333b3013a02809f9db6c086118b3fcbbd9dba).

**Comment by Lippiero** [comment]
I have the same error logs which photinus mentioned in his initial post. Setting get_source and get_sources to false don't let the errors come up... so far - so good

I am running HA in a python virtual environment on an arm64 Odroid C2 with Ubuntu 16.04 LTS.

Is there a chance to get the Source and Sources functionality in the future?

**Comment by JeffLIrion** [comment]
@Lippiero it's not likely. I still don't understand why a seemingly small percentage of people get those errors, so I don't know a better way to fix them. But anyone is welcome to submit a pull request.
